### PR TITLE
Missing help files for Check integrity and for Cleanup entries; MIT License; FR: label all outdated files

### PR DESCRIPTION
**Pull request by mlep**
I have not figure out (yet) how to get my different commits into different PRs...

### CODE REVIEW

**Comment by Siedlerchr** [comment]
One branch -> one PR.
Commits to one branch A all land into the same PR if you create a PR for Branch A.

I have no idea why the travis CI test fails,

**Comment by koppor** [comment]
I merge, but `License.md` should be put in the root of the directory as `LICENSE.md`. I would vote for [CC-by-4.0](http://creativecommons.org/licenses/by/4.0/)

**Comment by mlep** [comment]
- About the type of license: see https://github.com/JabRef/help.jabref.org/issues/11#issuecomment-243151983 . Of course, we can change it (just let me know).
- About the file location: so we need two files: en/License.md (for the help as viewed by the user) and /LICENSE.md (for developers), right?

**Comment by mlep** [comment]
@Siedlerchr: this is what I tried to do, and --- obviously --- failed...

**Comment by Siedlerchr** [comment]
@mlep  Some minsunderstanding 
Help contents are under CC license, therefore the Licence.md file in the root folder here.
However, there is **no** JabRef-Program-Help-Page for the licence.
The licence name is just in the code in the about dialog.

**Comment by Siedlerchr** [comment]
licences

**Comment by mlep** [comment]
@Siedlerchr Thank you for the clarification. Should a license information appears in https://help.jabref.org/en/ ?

**Comment by Siedlerchr** [comment]
Hm, maybe you can add one entry about the JabRef License and then just link
to https://github.com/JabRef/jabref/blob/master/LICENSE.md

In the meantime I will add a short sentence about the Help Content Licence
in the Readme

2016-10-03 18:51 GMT+02:00 MLEP <notifications@github.com>:

**Pull request merged**
