### PR TITLE
Update status.md

### PR DESCRIPTION
**Pull request by sakshamtaneja21**
- [ ] If you added a new item or changed the localization: Did you run `c:\Python27\python _scripts\automate.py update -e`?

### CODE REVIEW

**Comment by koppor** [comment]
See my comment on #230

**Comment by sakshamtaneja21** [comment]
why have you put this invalid

**Comment by koppor** [comment]
Maybe the word "invalid" is too hard. The pull request contained the addition of **one empty line**. This is good enough to merged in.

Do you know hacktoberfest? They have "Quality standards". See https://hacktoberfest.digitalocean.com/details.

The motto is "Quality" is key. 

grafik

Touching less then 10 letters (!) is too less to count towards a T-Shirt.

This is your pull requests count at your profile:

grafik

I think, you have enough other pull requests.

**Comment by sakshamtaneja21** [comment]
yes

**Comment by sakshamtaneja21** [comment]
may i know how will i warn jabref tshirt

**Comment by sakshamtaneja21** [comment]
how can I get an invite of your GitHub organization as a member

**Comment by koppor** [comment]
Developers are added to the JabRef organization after multiple contributions spanning multiple months. As far as I can remember, your PRs are the first on JabRef. Maybe, you can start coding and fixing things? There are many to choose from available at https://github.com/JabRef/jabref/issues. A developer within the organization got to know the internals of JabRef. Be invited to dive into it by working on issues.

**Pull request merged**
