### PR TITLE
Change references from MySQL to MariaDB

### LINKED ISSUE #201: Mention MariaDB as well as MySQL
There are a small number of references to [MySQL](https://github.com/JabRef/help.jabref.org/search?q=mysql&unscoped_q=mysql) that might warrant an update given JabRef/jabref#4746.

### PR DESCRIPTION
**Pull request by sameshl**
- [ ] If you added a new item or changed the localization: Did you run `c:\Python27\python _scripts\automate.py update -e`?

made appropriate changes for the transition from `MySQL` to `MariaDB`.
closes #201

### CODE REVIEW

**Comment by matthiasgeiger** [comment]
Thanks for your effort so far! 

However, @JabRef/developers am I right, that Maria DB is only an additional option an not an replacement for MySQL? As I'm not using the shared DB connection I'm not quite sure - but that is my understanding of https://github.com/JabRef/jabref/pull/4746.

**Comment by koppor** [comment]
JabRef works with both MySQL and MariaDB.

@sameshl Please keep the quality of the updated help page. Is is good that you provide a list of MariaDB hostings. However, as reader, I cannot see which one it is --> Is there any free (!) MariaDB hosting service? Can you list it?

I am not sure why MariaDB is required "at least version 2.4.0"? The homepage of MaridaDB does not list versions older than 5.1 (see https://mariadb.com/kb/en/library/mariadb-server-52/) Where did you get 2.4.0 from? How did you try it?

**Comment by koppor** [comment]
I will flag the PR as "invalid" until the issues are resolved.

**Comment by sameshl** [comment]
I am sorry for not keeping up the standard of the help page. I will make sure I make proper amendments so I correct it.

>  Is is good that you provide a list of MariaDB hostings. However, as reader, I cannot see which one it is --> Is there any free (!) MariaDB hosting service? Can you list it?

The thing is I have not used MariaDB so I didn't know which to suggest. So I thought the best might be link to their official page regarding the same. If you know any free service, please let me know. That would be appreciated.

> I am not sure why MariaDB is required "at least version 2.4.0"? The homepage of MaridaDB does not list versions older than 5.1 (see https://mariadb.com/kb/en/library/mariadb-server-52/) Where did you get 2.4.0 from? How did you try it?

The thing is I saw it from this https://github.com/JabRef/jabref/pull/4746/files#diff-c197962302397baf3a4cc36463dce5eaR118 and probably got confused the version of MariaDB connector and MariaDB. My bad.

**Comment by koppor** [comment]
So this is a great opportunity to start with MariaDB 👍. With your research, the whole community can benefit!

**Comment by koppor** [comment]
No updates on this. What a pity. I hope, you enjoyed #hacktoberfest nevertheless.

**Pull request closed without merging**
