### PR TITLE
FR: index: translation of subsection title

### PR DESCRIPTION
**Pull request by mlep**
(After figuring out how to create a new PR for a new commit... )

### CODE REVIEW

**Comment by Siedlerchr** [comment]
The translation of the  category names are handled in the script's global json file 
https://github.com/JabRef/help.jabref.org/blob/gh-pages/_scripts/localization/fr.json

**Comment by mlep** [comment]
I have just learn something!

**Comment by koppor** [comment]
I'm currently doing it on the mater branch.

**Comment by koppor** [comment]
@mlep - We need translations for

```
Language file 'fr' has an empty key 'Back to main page'
Language file 'fr' has an empty key 'Back to table of contents'
Language file 'fr' has an empty key 'Collaborative work'
``

**Comment by mlep** [comment]
They are (same order):
- Retour à la page d'accueil
- Retour à la table des matières
- Travail collaboratif

**Pull request closed without merging**
