### PR TITLE
Updating Japanese help

### PR DESCRIPTION
**Pull request by kojiyokota**
add new Japanese translations for
- FindDuplicates.md
- MedlineRIS.md
- SharedBibFile.md
and update
- index.md

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Thanks for your contribution! :+1:  

@bartsch-dev  Could you integrate this into #77 ? (If I merge it, I would delete our cname)

@kojiyokota  Please consider creating a branch for your next changes. Makes it easier for us and yourself, because now we have the problem that you updated your cname on your (master/ghpages) branch and want to merge it in here. So we then would get your cname changes here as well..

https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/
PS: You can ignore the CNAME warning safely.

**Comment by bartsch-dev** [comment]
I extracted the translations of the categories, the names of the links in the index file will be generated from the frontmatter of each file.

**Comment by koppor** [comment]
The `CNAME` change should not be in the merge. The Japanese help files will still be hosted here. I will revert that commit after merging.

**Comment by koppor** [comment]
The CNAME thing seems to be more difficult than expected. In our `.gitignore`, we have

    #try to avoid "Page build warning"s at contributors
    #see for background information https://github.com/trek/beautiful-open/issues/43
    CNAME

However, our interpretation of the solution still seems to be not working.

**Pull request merged**
