### PR TITLE
EN: searching: regular expressions explained

### PR DESCRIPTION
**Pull request by mlep**
A partial response to Issue https://github.com/JabRef/help.jabref.org/issues/32 .
- Inclusion of regular expressions based on https://sourceforge.net/p/jabref/wiki/Searching_with_regular_expressions/
- Some change in the structure to make it more convenient

Question: Please, can you confirm that search strings which include single quotes (any types, i.e. ` and ') do not need any specific attention?

### CODE REVIEW

**Comment by Siedlerchr** [comment]
As far as I can tell:
Special symbols: `"  \  .  $ ^`
http://docs.oracle.com/javase/6/docs/api/java/util/regex/Pattern.html

**Comment by mlep** [comment]
Well, I am no java programmer...
In the examples taken from the wiki, { is escaped too, so my guess is that { is also a special symbol.
I got the list from <https://docs.oracle.com/javase/tutorial/essential/regex/literals.html>.
And I found the same list here: <https://stackoverflow.com/questions/14134558/list-of-all-special-characters-that-need-to-be-escaped-in-a-regex>

**Comment by Siedlerchr** [comment]
Yes, the list is correct.  I am only unsure about the angle brackets (< >)




2016-10-27 23:20 GMT+02:00 MLEP <notifications@github.com>:

**Comment by mlep** [comment]
@JabRef/developers : any consensus about the special characters?

**Comment by mlep** [comment]
@JabRef/developers: could we move forward on this PR?

**Comment by matthiasgeiger** [comment]
Sorry for not answering, yet.

I don't know why `< >` are listed as special characters at java.oracle.com but there is no need to escape these in JabRef. So we can remove them here from the list.

Apart from that: Good work! I've just two suggestions: Can you add a Screenshot of the Search bar? (Please use a 3.7dev version with the search bar in the menu bar) And I would reorder the "settings" sections to be in sync with the actual order of settings (Global, RegEx, case sensitive, Filter/Float).

**Comment by mlep** [comment]
It looks like some features have changed:
-  the search bar is always displayed (no toggle anymore)
- <kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>F</kbd> is not active anymore (before, it was running a global search with the current search string).
Could you confirm, please?

**Comment by matthiasgeiger** [comment]
Yes. The searchbar is always visible - but <kbd>CTRL</kbd>+<kbd>F</kbd> will move the cursor to the search so this shortcut is still quite usable.

<kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>F</kbd> seems to do nothing at the moment. I would have suspected that it will toggle the "search globally" option... - will check whether I can add this functionality quickly.

**Comment by mlep** [comment]
@matthiasgeiger Thanks. I will change/add all these.

**Comment by matthiasgeiger** [comment]
I have reactivated the CTRL+SHIFT+F shortcut with the following semantics:

Activates the global search setting and the cursor jumps to the search field.

**Comment by mlep** [comment]
Great!

**Comment by mlep** [comment]
- <> removed from special characters
- screenshot added
- shuffling of some sections for more coherence
- rewriting of the first § for clarification

**Comment by matthiasgeiger** [comment]
👍  Great!

I've directly committed some small changes.

As the global search bar is not yet released we should wait with merging until 3.7 is released.

**Comment by koppor** [comment]
I merged, because we now support `since: 3.7` in the YAML front matter (refs #121)

**Pull request merged**
