### PR TITLE
Spires->INSPIRE and changed German index order

### PR DESCRIPTION
**Pull request by Siedlerchr**
Spires->INSPIRE and added it to the German index file, too.
Changed order of German files, so that it is the same as the english

### CODE REVIEW

**Comment by koppor** [comment]
Could you please squash all commits into one? We have a [howto](https://github.com/JabRef/jabref/wiki/Tools#rebase-everything-as-one-commit-on-master), which should also be applicable here.

Then, it's easier for reviewing :innocent: 

I think, this PR is an update to #9, isn't it? - May I ask if it was possible in the future that just update your old branch (here: `patch-1`) instead of creating a new pull request? :innocent:

**Comment by Siedlerchr** [comment]
Well, I first started with #9 then I noticed that GitHub creates a new branch every time I edit a file...
So I decided to create a new branch and have all commits in one place...
I did not yet clone the repo locally, so I did this with the limited capabilities of the website.
Will try to do this by tomorrow.

**Comment by Siedlerchr** [comment]
I think I figured the rebasing out, squashed all changes into one commit;)

**Comment by simonharrer** [comment]
:+1:

**Comment by Siedlerchr** [comment]
I will change the other index files, too

**Comment by koppor** [comment]
I am not aware of a solution. The only idea would be to delete the CNAME file in your fork. As you work on other branches, this shouldn't be an issue.

**Comment by Siedlerchr** [comment]
Fixed some Search & Replace error
However, when I delete the CNAME this will creates problems with merging the changes from upstream etc.
The simplest solution would be to add the CNAME file to the gitignore-file that should help:
https://github.com/trek/beautiful-open/issues/43

**Comment by koppor** [comment]
I'll try the .gitignore solution.

**Pull request merged**
