### PR TITLE
Add contribution guide

### PR DESCRIPTION
**Pull request by matthiasgeiger**
Implements https://github.com/JabRef/jabref/issues/1255

Please feel free to comment and improve.

Screenshot of the locally built page (with some strange encoding errors :-1:):
bildschirmfoto am 2016-04-25 um 22 15 42

### CODE REVIEW

**Comment by matthiasgeiger** [comment]
@JabRef/developers any objections before merging this in?

**Comment by koppor** [comment]
Filename: `CONTRIBUTING`, as [this is the supported way of GitHub](https://help.github.com/articles/setting-guidelines-for-repository-contributors/). It seems that `CONTRIBUTING.md` is not supported any more, even if [a blog of 2012](https://github.com/blog/1184-contributing-guidelines) names it.

**Comment by matthiasgeiger** [comment]
I thought about this, but decided to create a "normal" page which can be translated as the other help pages - or is a single English contribution guide enough?

**Comment by stefan-kolb** [comment]
CONTRIBUTING.md should also work. See https://github.com/stefan-kolb/nucleus/issues/new

**Comment by koppor** [comment]
Ah, also not displayed at https://github.com/stefan-kolb/nucleus/pulls/new. Seems to be a systematic issue.

**Comment by koppor** [comment]
English guide is enough. :smiley:  In case we add translations, we can link them from CONTRIBUTING.md.

**Comment by matthiasgeiger** [comment]
All right then I'll change this later...

**Pull request merged**
